# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0D1926)
$foreground = rgb(B4E1FD)
$color0 = rgb(363636)
$color1 = rgb(FF0883)
$color2 = rgb(83FF08)
$color3 = rgb(FF8308)
$color4 = rgb(0883FF)
$color5 = rgb(8308FF)
$color6 = rgb(08FF83)
$color7 = rgb(B6B6B6)
$color8 = rgb(424242)
$color9 = rgb(FF1E8E)
$color10 = rgb(8EFF1E)
$color11 = rgb(FF8E1E)
$color12 = rgb(1E8EFF)
$color13 = rgb(8E1EFF)
$color14 = rgb(1EFF8E)
$color15 = rgb(C2C2C2)
