-- Generated by nwg-displays on 2026-06-11 at 13:39:41. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@280.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@144.0",
    position = "1920x0",
    scale = 1.0
})
