-- Generated by nwg-displays on 2026-06-06 at 18:53:09. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-2",
    default = true
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "DP-2"
})
